sudo: required
dist: trusty

language: php
php:
  - 7
jdk: openjdk8

env:
  - DB=6.2.4 ES_PKG=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb

before_install:
  - curl -O $ES_PKG && sudo dpkg -i --force-confnew $(printf 'elasticsearch-%s.deb' $DB)
  - sudo service elasticsearch start
  - until curl localhost:9200; do sleep 1; done

install:
  - composer install

script: ./bin/phpunit --coverage-text

notifications:
  email: false
