sudo: required
dist: trusty

language: php
php:
  - 5.6
  - 7

env:
  - DB=5.0.0 ES_PKG=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.deb
  - DB=5.2.1 ES_PKG=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.1.deb

before_install:
  - curl -O $ES_PKG && sudo dpkg -i --force-confnew $(printf 'elasticsearch-%s.deb' $DB)
  - sudo service elasticsearch start
  - until curl localhost:9200; do sleep 1; done

install:
  - composer install

script: ./bin/phpunit --coverage-text

notifications:
  email: false
