language: php
php:
  - 5.3
  - 5.4

services:
  - elasticsearch

before_script:
  - composer install --dev


script: if [ $(phpenv version-name) = "5.3" ]; then ./bin/phpunit -c phpunit.5.3.xml --coverage-text; else ./bin/phpunit --coverage-text; fi

notifications:
  email: false
