sudo: required
dist: precise

language: php
php:
  - 5.5
  - 5.6
  - 7

env:
  - DB=1.7.1 ES_PKG=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.deb
  - DB=2.2.0 ES_PKG=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.2.0/elasticsearch-2.2.0.deb

before_install:
  - curl -O $ES_PKG && sudo dpkg -i --force-confnew $(printf 'elasticsearch-%s.deb' $DB)
  - sudo service elasticsearch start

install:
  - composer install --dev

script: ./bin/phpunit --coverage-text

notifications:
  email: false
